version: '2'
services:
  mysql:
    container_name: graphql_mysql
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql